#echo $(pwd)

cmake -Wno-dev \
    -DCMAKE_VERBOSE_MAKEFILE=0 \
    -DCMAKE_SYSROOT=${SYSROOT_PATH} \
    -DCMAKE_FIND_ROOT_PATH=${SYSROOT_PATH} \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
    -DCMAKE_SYSTEM_NAME=Generic \
    -DCMAKE_C_COMPILER=${FAM_CC} \
    -DCMAKE_CXX_COMPILER=${FAM_CXX} \
    -DCMAKE_LINKER=${FAM_CC} \
    -DCMAKE_AR=${FAM_AR} \
    -DCMAKE_AS=${FAM_AS} \
    -DCMAKE_POSITION_INDEPENDENT_CODE=1 \
    -DENABLE_STATIC=1 \
    -DENABLE_SHARED=0 \
    -DWITH_JPEG8=1 \
    -DWITH_SIMD=1 \
    -DWITH_TURBOJPEG=0 \
    -DWITH_JAVA=0 \
    -DCMAKE_SYSTEM_PROCESSOR=${TARGET} || exit 1
#    -DCMAKE_C_FLAGS="${CFLAGS}" \
#    -DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
#    -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \

${MAKE_EXECUTABLE} clean
${MAKE_EXECUTABLE} -j${HOST_NPROC}
${MAKE_EXECUTABLE} install
# Installing the .pc file

# MANUALLY COPY PKG-CONFIG FILES
#cp ${BASEDIR}/src/${LIB_NAME}/build/pkgscripts/libjpeg.pc ${INSTALL_PKG_CONFIG_DIR} || exit 1
